import { Song, Artist, Album, Playlist, User } from '../types';

export const mockArtists: Artist[] = [
  {
    id: 'artist-1',
    name: 'Nova Waves',
    bio: 'Electronic music producer known for ambient soundscapes and ethereal beats.',
    imageUrl: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 1250000,
    genres: ['Electronic', 'Ambient', 'Synthwave'],
    verified: true,
  },
  {
    id: 'artist-2',
    name: 'The Echoes',
    bio: 'Indie rock band creating atmospheric melodies and introspective lyrics.',
    imageUrl: 'https://images.pexels.com/photos/1699161/pexels-photo-1699161.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 890000,
    genres: ['Indie Rock', 'Alternative'],
    verified: true,
  },
  {
    id: 'artist-3',
    name: 'Luna Sol',
    bio: 'Pop sensation blending modern R&B with experimental production.',
    imageUrl: 'https://images.pexels.com/photos/1391498/pexels-photo-1391498.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 2100000,
    genres: ['Pop', 'R&B'],
    verified: true,
  },
  {
    id: 'artist-4',
    name: 'Midnight Drive',
    bio: 'Retro synthwave artist bringing 80s nostalgia to modern audiences.',
    imageUrl: 'https://images.pexels.com/photos/1144256/pexels-photo-1144256.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 650000,
    genres: ['Synthwave', 'Electronic'],
    verified: true,
  },
  {
    id: 'artist-5',
    name: 'Velvet Horizon',
    bio: 'Dream pop duo crafting lush, layered soundscapes.',
    imageUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 450000,
    genres: ['Dream Pop', 'Shoegaze'],
    verified: false,
  },
  {
    id: 'artist-6',
    name: 'Atlas Sound',
    bio: 'Hip-hop producer and rapper pushing boundaries with experimental beats.',
    imageUrl: 'https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=800',
    followers: 1800000,
    genres: ['Hip-hop', 'Experimental'],
    verified: true,
  },
];

export const mockSongs: Song[] = [
  {
    id: 'song-1',
    title: 'Neon Dreams',
    artist: 'Nova Waves',
    artistId: 'artist-1',
    albumId: 'album-1',
    album: 'Digital Horizons',
    duration: 245,
    coverUrl: 'https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Electronic',
    releaseDate: '2024-03-15',
    plays: 3500000,
  },
  {
    id: 'song-2',
    title: 'Ethereal Nights',
    artist: 'Nova Waves',
    artistId: 'artist-1',
    albumId: 'album-1',
    album: 'Digital Horizons',
    duration: 198,
    coverUrl: 'https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Electronic',
    releaseDate: '2024-03-15',
    plays: 2100000,
  },
  {
    id: 'song-3',
    title: 'Fading Echoes',
    artist: 'The Echoes',
    artistId: 'artist-2',
    albumId: 'album-2',
    album: 'Silent Waves',
    duration: 223,
    coverUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Indie Rock',
    releaseDate: '2024-02-28',
    plays: 1800000,
  },
  {
    id: 'song-4',
    title: 'Moonlight',
    artist: 'Luna Sol',
    artistId: 'artist-3',
    albumId: 'album-3',
    album: 'Celestial',
    duration: 210,
    coverUrl: 'https://images.pexels.com/photos/1557652/pexels-photo-1557652.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Pop',
    releaseDate: '2024-04-01',
    plays: 5200000,
  },
  {
    id: 'song-5',
    title: 'Gravity',
    artist: 'Luna Sol',
    artistId: 'artist-3',
    albumId: 'album-3',
    album: 'Celestial',
    duration: 195,
    coverUrl: 'https://images.pexels.com/photos/1557652/pexels-photo-1557652.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Pop',
    releaseDate: '2024-04-01',
    plays: 4100000,
  },
  {
    id: 'song-6',
    title: 'Highway 85',
    artist: 'Midnight Drive',
    artistId: 'artist-4',
    albumId: 'album-4',
    album: 'Retro Future',
    duration: 267,
    coverUrl: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Synthwave',
    releaseDate: '2024-01-20',
    plays: 2700000,
  },
  {
    id: 'song-7',
    title: 'Velvet Sky',
    artist: 'Velvet Horizon',
    artistId: 'artist-5',
    albumId: 'album-5',
    album: 'Dreamscape',
    duration: 234,
    coverUrl: 'https://images.pexels.com/photos/1587927/pexels-photo-1587927.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Dream Pop',
    releaseDate: '2024-03-10',
    plays: 1200000,
  },
  {
    id: 'song-8',
    title: 'City Lights',
    artist: 'Atlas Sound',
    artistId: 'artist-6',
    albumId: 'album-6',
    album: 'Urban Chronicles',
    duration: 189,
    coverUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Hip-hop',
    releaseDate: '2024-02-14',
    plays: 3800000,
  },
  {
    id: 'song-9',
    title: 'Cosmic Flow',
    artist: 'Nova Waves',
    artistId: 'artist-1',
    albumId: 'album-1',
    album: 'Digital Horizons',
    duration: 256,
    coverUrl: 'https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Electronic',
    releaseDate: '2024-03-15',
    plays: 2900000,
  },
  {
    id: 'song-10',
    title: 'Sunset Boulevard',
    artist: 'Midnight Drive',
    artistId: 'artist-4',
    albumId: 'album-4',
    album: 'Retro Future',
    duration: 241,
    coverUrl: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg?auto=compress&cs=tinysrgb&w=800',
    audioUrl: '',
    genre: 'Synthwave',
    releaseDate: '2024-01-20',
    plays: 2200000,
  },
];

export const mockAlbums: Album[] = [
  {
    id: 'album-1',
    title: 'Digital Horizons',
    artistId: 'artist-1',
    artistName: 'Nova Waves',
    coverUrl: 'https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-03-15',
    songs: mockSongs.filter(s => s.albumId === 'album-1'),
    genre: 'Electronic',
  },
  {
    id: 'album-2',
    title: 'Silent Waves',
    artistId: 'artist-2',
    artistName: 'The Echoes',
    coverUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-02-28',
    songs: mockSongs.filter(s => s.albumId === 'album-2'),
    genre: 'Indie Rock',
  },
  {
    id: 'album-3',
    title: 'Celestial',
    artistId: 'artist-3',
    artistName: 'Luna Sol',
    coverUrl: 'https://images.pexels.com/photos/1557652/pexels-photo-1557652.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-04-01',
    songs: mockSongs.filter(s => s.albumId === 'album-3'),
    genre: 'Pop',
  },
  {
    id: 'album-4',
    title: 'Retro Future',
    artistId: 'artist-4',
    artistName: 'Midnight Drive',
    coverUrl: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-01-20',
    songs: mockSongs.filter(s => s.albumId === 'album-4'),
    genre: 'Synthwave',
  },
  {
    id: 'album-5',
    title: 'Dreamscape',
    artistId: 'artist-5',
    artistName: 'Velvet Horizon',
    coverUrl: 'https://images.pexels.com/photos/1587927/pexels-photo-1587927.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-03-10',
    songs: mockSongs.filter(s => s.albumId === 'album-5'),
    genre: 'Dream Pop',
  },
  {
    id: 'album-6',
    title: 'Urban Chronicles',
    artistId: 'artist-6',
    artistName: 'Atlas Sound',
    coverUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800',
    releaseDate: '2024-02-14',
    songs: mockSongs.filter(s => s.albumId === 'album-6'),
    genre: 'Hip-hop',
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: 'playlist-1',
    name: 'Chill Vibes',
    description: 'Relaxing tunes for unwinding after a long day.',
    coverUrl: 'https://images.pexels.com/photos/1590549/pexels-photo-1590549.jpeg?auto=compress&cs=tinysrgb&w=800',
    songs: [mockSongs[0], mockSongs[2], mockSongs[6]],
    createdBy: 'user-1',
    isPublic: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-04-20T15:30:00Z',
  },
  {
    id: 'playlist-2',
    name: 'Workout Energy',
    description: 'High-energy tracks to power through your workout.',
    coverUrl: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800',
    songs: [mockSongs[3], mockSongs[7], mockSongs[5]],
    createdBy: 'user-1',
    isPublic: true,
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-04-18T12:00:00Z',
  },
  {
    id: 'playlist-3',
    name: 'Late Night Drive',
    description: 'Perfect soundtrack for midnight adventures.',
    coverUrl: 'https://images.pexels.com/photos/1363876/pexels-photo-1363876.jpeg?auto=compress&cs=tinysrgb&w=800',
    songs: [mockSongs[5], mockSongs[9], mockSongs[1]],
    createdBy: 'user-1',
    isPublic: true,
    createdAt: '2024-03-01T20:00:00Z',
    updatedAt: '2024-04-15T22:00:00Z',
  },
];

export const mockUser: User = {
  id: 'user-1',
  username: 'musiclover',
  email: 'user@example.com',
  photoUrl: 'https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=400',
  bio: 'Music enthusiast exploring new sounds every day.',
  isPremium: false,
  playlists: ['playlist-1', 'playlist-2', 'playlist-3'],
  likedSongs: ['song-1', 'song-3', 'song-4', 'song-7'],
  followedArtists: ['artist-1', 'artist-3', 'artist-4'],
  createdAt: '2023-06-15T12:00:00Z',
};
